---
output: github_document
---

# DBCS
An R package for doing fun sequntial/anytime-valid inference in linear models.

[https://arxiv.org/abs/2210.08639](https://arxiv.org/abs/2210.08639).

All code was written and edited by Dae Woong Ham (daewoongham@g.harvard.edu)

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("rainersachs/NASA2")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r}
library(DBCS)
```

## Data generating process 
```{r}
signup_sim = function(n, baseline = 0.15, trt_effect = -0.10, seed = 1) {
  set.seed(seed)
  Y0 = sample(c(0,1), size = n, replace = TRUE, prob = c(1 - baseline, baseline))
  Y1 = sample(c(0,1), size = n, replace = TRUE,
              prob = c(1 - baseline - trt_effect, baseline + trt_effect))

  W = sample(c(0,1), size = n, replace = TRUE)
  y = Y0
  y[W == 1] = Y1[W == 1]
  df = data.frame(W, y)
  return(df)
}
```

## Design-Based CS
```{r}
# Exact
exact_CS = DB_CS(df, treatment, response, nonasymp = TRUE, M = 1)
# Asymptotic
asymp_CS = DB_CS(df, treatment, response)
```

